--- #YAML:1.0
name:                Color-Spectrum-Multi
version:             0.02
abstract:            simple L<Color::Spectrum> wrapper to handle fading
license:             perl
author:              
    - David Precious <davidp@preshweb.co.uk>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Color::Spectrum:               0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
